### ISSUE TITLE
Create Account Doctor and Admin

### ISSUE THREAD

**Issue by medihubmithang** [muhammadsemeer/clinic-management-system#1]
How to create account doctor and admin?
May you help me?

**Comment by muhammadsemeer** [comment]
You need to add an email and a password encrypted using bcrypt into your admin collection on the database.
Then You can log in to the admin account with that email and password.

After that admin can create a doctor account with an email id, the login credentials will be mailed to that email by the server itself. You can log in to doctor account using that credentials

I Hope You understand.

Happy Coding 😄
